### ISSUE TITLE
Event specific SEO tags

### ISSUE THREAD

**Issue by biharygergo** [hackjunction/JunctionApp#65] opened 2020-02-17 08:30 UTC
It would greatly increase the SEO of hackplatform pages if the individual events had their own meta tags depending on the event's name, description and cover image. This would also help in sharing to social networks and between competitors. 

I see two ways of doing this: 
1) The easy way: Change the meta tags from js when an event landing page is loaded. Pros: easy to implement Cons: has worse SEO, because it needs Javascript to render the meta tags. Also, Facebook crawlers don't do javascript yet I believe. 
2) The good way: Render the <meta> from node.js and inject them into the React template. This would mean that there should be some regex logic to catch event landing pages and dinamically load meta tags based on that. Pros: Works for all search engines. Cons: The coupling between backend and frontend will get stronger.

**Comment by biharygergo** [comment] 2020-02-17 08:32
Going a step further, it would also be cool if we had a section on the event customization page to insert custom Javascript to the template before the end of the </body>. This is useful for adding custom trackers.

**Comment by lappalj4** [comment] 2020-02-17 08:35
Sounds cool. What we've been using on some websites is a prerender service such as prerender.io which allows us to do (1) but without the cons. But if you have an idea on how to implement (2) I would be all for that!

**Comment by Earlo** [comment] 2020-05-22 10:51
also discussed here #80

**Comment by pholm** [comment] 2020-09-04 11:52
Duplicate of #80

**Closed** 2020-09-23 08:51 UTC
Labels: enhancement, good first issue, nice to have
